---
image: Visual Studio 2019
version: 1.0.{build}.{branch}

build: false

branches:
  only:
    - main

matrix:
  fast_finish: true

# We always use a 64-bit machine.
platform:
  - x64

environment:

  global:

    MINGW_32: C:\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin
    MINGW_64: C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin
    DEFAULT_PYTHON: "C:\\Python39-x64"

  matrix:

    # See: https://www.appveyor.com/docs/installed-software/#python

    - NOX_SESSION: "unit-3.7-32"
    - NOX_SESSION: "unit-3.7"
    - NOX_SESSION: "unit-3.8-32"
    - NOX_SESSION: "unit-3.8"
    - NOX_SESSION: "unit-3.9-32"
    - NOX_SESSION: "cover"
    - NOX_SESSION: "functional-3.9"
    - NOX_SESSION: "doctest"

install:
  - echo "Filesystem root:"
  - dir C:\

  # Make 64-bit Python 3.9 the "default" Python.
  - "SET PATH=%DEFAULT_PYTHON%;%DEFAULT_PYTHON%\\Scripts;%PATH%"

  # Workaround for CMake not wanting sh.exe on PATH for MinGW
  - set PATH=%PATH:C:\Program Files (x86)\Git\bin;=%
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Append MinGW to the PATH of this build so ``gfortran`` is visible
  # to ``numpy.distutils``.
  - ps: |
      $NOX_SESSION = $env:NOX_SESSION
      If ($NOX_SESSION.EndsWith("-32")) {
          $MINGW = $env:MINGW_32
      } Else {
          $MINGW = $env:MINGW_64
      }
      $env:Path += ";$MINGW"

  # Packaging requirements
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade wheel

  # Install the build dependencies of the project.
  - python -m pip install --upgrade "nox >= 2020.12.31"

test_script:
  - python -m nox -s %NOX_SESSION%

cache:
  # Use the appveyor cache to avoid re-downloading large archives.
  - '%LOCALAPPDATA%\pip\Cache'
