---
language: generic
os: osx
osx_image: xcode11.3  # This is latest as of January 11, 2020

addons:
  homebrew:
    packages:
      - gcc  # For `gfortran`

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.6
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.7
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.8

install:
  - source scripts/macos/travis-setup.sh

script:
  - scripts/macos/test.sh
