---
language: generic
os: osx
osx_image: xcode11.4 # This is latest as of May 19, 2020

branches:
  only:
    - master

addons:
  homebrew:
    packages:
      - gcc # For `gfortran`

matrix:
  include:
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.6
        - VIRTUALENV_NO_DOWNLOAD=true
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.7
        - VIRTUALENV_NO_DOWNLOAD=true
    - os: osx
      language: generic
      env:
        - PY_VERSION=3.8
        - VIRTUALENV_NO_DOWNLOAD=true

install:
  - source scripts/macos/travis-setup.sh

script:
  - scripts/macos/test.sh
