---
name: macOS

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  schedule:
  # Scheduled workflows run on the latest commit on the default or base branch
  - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manually triggering workflow'
        required: true

jobs:
  ci:
    runs-on: macos-latest
    env:
      PY_VERSION: '${{ matrix.python-version }}'
      PY_BIN_DIR: '/Library/Frameworks/Python.framework/Versions/${{ matrix.python-version }}/bin'
    strategy:
      matrix:
        python-version:
        - '3.7'
        - '3.8'
        - '3.9'
    steps:
    - uses: actions/checkout@v2
    - name: Install `gcc`
      run: |
        brew install gcc
        brew unlink gcc
        brew link gcc
    - name: Run "install" to setup Python environment and tooling
      run: scripts/macos/setup.sh
    - name: Run tests
      run: scripts/macos/test.sh
    - uses: actions/cache@v2
      with:
        path: ~/Library/Caches/pip
        key: macos-pip
